### ISSUE TITLE
.ea-php-cli.cache broken “data” symlinks

### ISSUE THREAD

**Issue by cssjoe** [CpanelInc/php-cli#2]
Since receiving the update to "ea-php-cli-1.0.0-3.3.1.cpanel.x86_64", I have been seeing broken symlinks being created in directories where PHP scripts were run via CLI.  I know that the ea-php-cli package determines which PHP version to use in the execution, and the new functionality caches the result to speed up future execution.  That's all good, but the broken symlinks that are used are causing some issues with software (such as WordPress); some plugin updates fail due to bad permission detection.  I believe that the issue is that other software examines the symlink target, which does not exist.

Here is the pull request that brought in the cache changes:
https://github.com/CpanelInc/php-cli/commit/883e8f1f3f37998d4501de4d4276c8a9d290fae3

It may be a better idea to store the cache information in the "~/.cpanel" directory instead of in users' website directories.

**Comment by drmuey** [comment]
The symlinks are used as a very fast way to get the value for a given directory. Its ok if they are broken as they are not intended to point to a file.

Since nothing but php-cli consumes them they should not interfere with anything else, can you elaborate on any problems they are causing?

i.e. when and why is wordpress trying to resolve an arbitrary symlink that it does not use?

**Comment by drmuey** [comment]
whups, wrong button ;)

**Comment by drmuey** [comment]
Simple workaround if any one does experience an issue:

1. Delete symlink
2. Do the thing that for some reason cares about arbitrary symlinks named as a hidden file that is unrelated to itself

**Comment by drmuey** [comment]
Idea is instead of `~/public_html/foo/bar/baz/.ea-php-cli.cache`
do something like `~/.cpanel/php-cli/public_html/foo/bar/baz/.ea-php-cli.cache`.

Would need cleanup of old `.ea-php-cli.cache` ideally.

**Comment by cssjoe** [comment]
I'm looking into making a patch/fix for WordPress Core detecting the symlinks as an issue, causing updates to abort.

The actual error that I have been seeing (on multiple cP/EA4 servers) is:
> An error occurred while updating <plugin_name>: The update cannot be installed because we will be unable to copy some files. This is usually due to inconsistent file permissions.
... and lists the symlink paths in the message.

I do like the idea of using `~/.cpanel/ea-php-cli/...` instead of in the live directories.  Of course, a cleanup of the old symlinks would be recommended.

**Comment by drmuey** [comment]
Yeah a wordpress patch to just be ok w/ broken symlinks would be ideal since that sort of mechanism is used by a number of things.
 
Does that error go away when you remove the `.ea-php-cli.cache`?

**Comment by cssjoe** [comment]
Yes, deleting the symlinks will resolve the issue, and let updates succeed.
`find ~/ -type l -name ".ea-php*" -delete`

**Comment by cssjoe** [comment]
This issue could happen in other web software, so it should still be fixed by cPanel.
As for WordPress, I did submit a ticket with a patch: https://core.trac.wordpress.org/ticket/46040
Thank you!

**Comment by telmanik** [comment]
Are these files suppose to be set with a permission of 777?

**Comment by cssjoe** [comment]
Thank you.  I just noticed that it was updated 10 days ago.
I see that the links are now being created in the "~/.cpanel/ea-php-cli/" directory.  Although the old existing symlinks were not cleaned up.
Also, I receive the following perl warnings:
> Use of uninitialized value $home in quotemeta at /var/cpanel/ea4/ea_php_cli.pm line 228.
Use of uninitialized value $home in concatenation (.) or string at /var/cpanel/ea4/ea_php_cli.pm line 228.

https://github.com/CpanelInc/php-cli/blob/f24af395f5d3657e7d5fd4d74fc7be48ebbe9425/SOURCES/ea_php_cli.pm#L228

**Comment by drmuey** [comment]
Thanks @cssjoe, 

I am unable to reproduce. Can you send reproduction steps?

I actually suspect a local FS issue because:
* the old cache is removed anytime the new cache is created/goes stale and is recreated
* `$home` comes from a `getpwuid()` on the uid from a `stat()` on the path involved

**Comment by cssjoe** [comment]
It appears to happen when an executable PHP file outside the home directory (such as "/usr/local/bin/wp") is executed.
In an strace, I found:
> sendto(3, "\2\0\0\0\v\0\0\0\7\0\0\0passwd\0", 19, MSG_NOSIGNAL, NULL, 0) = 19
poll([{fd=3, events=POLLIN|POLLERR|POLLHUP}], 1, 5000) = 1 ([{fd=3, revents=POLLIN|POLLHUP}])
recvmsg(3, {msg_name(0)=NULL, msg_iov(2)=[{"passwd\0", 7}, {"\310O\3\0\0\0\0\0", 8}], msg_controllen=24, [{cmsg_len=20, cmsg_level=SOL_SOCKET, cmsg_type=SCM_RIGHTS, [4]}], msg_flags=MSG_CMSG_CLOEXEC}, MSG_CMSG_CLOEXEC) = 15

and:
> write(2, "Use of uninitialized value $home"..., 89Use of uninitialized value $home in quotemeta at /var/cpanel/ea4/ea_php_cli.pm line 228.
) = 89
write(2, "Use of uninitialized value $home"..., 107Use of uninitialized value $home in concatenation (.) or string at /var/cpanel/ea4/ea_php_cli.pm line 228.
) = 107
lstat("/.cpanel/ea-php-cli/usr/local/bin/.ea-php-cli.cache", 0x7ffa3af7da90) = -1 ENOENT (No such file or directory)

Here is a test:
`# echo -e '#!/usr/bin/env php\n<?php\necho "Hello world";\n' > /usr/local/bin/test.php; chmod 755 /usr/local/bin/test.php`
`$ /usr/local/bin/test.php`
Use of uninitialized value $home in quotemeta at /var/cpanel/ea4/ea_php_cli.pm line 228.
Use of uninitialized value $home in concatenation (.) or string at /var/cpanel/ea4/ea_php_cli.pm line 228.
Hello world

**Comment by cssjoe** [comment]
I did find that a lot of directories and files had owner:group as 500:500, where there is no user with that uid or gid.  I fixed them all to root:root (0:0), and no longer get the warnings.  I'm not sure how or when the ownership changed, but it's fixed now.
Also, the old cache file cleanup is working.
Thank you!  I believe that this issue is resolved.

**Comment by drmuey** [comment]
@cssjoe awesome, thanks ;)
